*** Settings ***
Documentation    API baseline of es-bills

Resource    	  ../init.robot

Force Tags      Es-Bills
Test Setup      Test Setup
Suite Setup     Suite Setup
Test Timeout    ${TEST_TIMEOUT}

*** Variables ***
${bill_period}    1899-01

*** Test Cases ***
es-bills - get - invalid - get bill with invalid fields
    [Tags]    FET
    [Template]    Verify Es Bill Get With Invalid Fields
    402010005    Payment status should be 0 ~ 1.                                          payment_status=-1
    402010005    Payment status should be 0 ~ 1.                                          payment_status=2
    402010005    Invalid payment type                                                     payment_type=0
    402010005    Invalid payment type                                                     payment_type=6
    402010006    bill_status must be in 0 1 2 3 4 5 6                                     bill_status=-1
    402010006    bill_status must be in 0 1 2 3 4 5 6                                     bill_status=7
    402010006    delivery_method must be in 1 2                                           delivery_method=0
    402010006    delivery_method must be in 1 2                                           delivery_method=3
    402010006    request_data_type must be in 0 1                                         request_data_type=-1
    402010006    request_data_type must be in 0 1                                         request_data_type=2
    402010006    printInvoice],0]; default message [must be greater than or equal to 0    print_invoice=-1
    402010006    printInvoice],1]; default message [must be less than or equal to 1       print_invoice=3

es-bills - get - valid - get bill by es_bill_id
    [Tags]    test
    ${resp} =       Create Es Bill    ${EsBill}    ${EsContract}    ${User}    ${Scooter.scooter_id}
    ${bill_id} =    Set Variable      ${resp.json()['data'][0]['es_bill_id']}
	${resp} =       Es Bills Get      es_bill_ids=${bill_id}    request_data_type=${1}
    Verify Status Code As Expected       ${resp}                                    200
    Verify Response Contains Expected    ${resp.json()['data'][0]['es_bill_id']}    ${bill_id}
    Verify Schema    es-bill.json    esBillWithScooter    ${resp.json()}

es-bills - get - valid - get bill by accumulated = 0
    [Setup]    Create Accumulated Es Bill
    ${resp} =    Es Bills Get      bill_period=${EsBill_new.bill_period}    request_data_type=${1}    accumulated=0    bill_status=${None}
    Verify Status Code As Expected       ${resp}                                     200
    Verify Response Contains Expected    ${resp.json()['data'][0]['accumulated']}    0

es-bills - get - valid - get bill by accumulated = 1
    [Setup]    Create Accumulated Es Bill
    ${resp} =    Es Bills Get      bill_period=${EsBill.bill_period}    request_data_type=${1}    accumulated=1    bill_status=${None}
    Verify Status Code As Expected       ${resp}                                    200
    Verify Response Contains Expected    ${resp.json()['data'][0]['es_bill_id']}     ${accumulated_bill_id}
    Verify Response Contains Expected    ${resp.json()['data'][0]['accumulated']}    1

es-bills - get - valid - get bill by bill_status and print_invoice = 0
    ${bill_id} =    Create Es Bill With Required Fields        print_invoice=0
	${resp} =       Es Bills Get    bill_period=${EsBill.bill_period}    bill_status=1    request_data_type=${1}    print_invoice=0
    Verify Status Code As Expected       ${resp}                                       200
    Should Contain                       ${{str(${resp.json()['data']})}}              ${bill_id}
    Verify Response Contains Expected    ${resp.json()['data'][0]['print_invoice']}	   0

es-bills - get - valid - get bill by bill_status and print_invoice = 1
    ${bill_id} =    Create Es Bill With Required Fields        print_invoice=1
    ${resp} =       Es Bills Get    user_id=${User.user_id}    bill_status=1    request_data_type=${1}    print_invoice=1
    Verify Status Code As Expected       ${resp}                                       200
    Verify Response Contains Expected    ${resp.json()['data'][0]['es_bill_id']}       ${bill_id}
    Verify Response Contains Expected    ${resp.json()['data'][0]['print_invoice']}	   1

es-bills - add - invalid - create es bill with invalid bill_status
    [Tags]    FET
    [Template]    Verify Es Bill Post With Invalid Fields
    402010006    bill_status must be in 1    bill_status=0     user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    bill_status must be in 1    bill_status=2     user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    bill_status must be in 1    bill_status=3     user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    bill_status must be in 1    bill_status=4     user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    bill_status must be in 1    bill_status=5     user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    bill_status must be in 1    bill_status=6     user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    bill_status must be in 1    bill_status=7     user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    bill_status must be in 1    bill_status=-1    user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0

es-bills - add - invalid - create es bill with invalid fields
    [Tags]    FET
    [Template]    Verify Es Bill Post With Invalid Fields
    402010006    printInvoice],0]; default message [must be greater than or equal to 0    user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0            addon_price_amount=0             promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0    print_invoice=-1
    402010006    printInvoice],1]; default message [must be less than or equal to 1       user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0            addon_price_amount=0             promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0    print_invoice=3
    402010006    taxableAmount],true,org.springframework.validation                       user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0            addon_price_amount=0             promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0    taxable_amount=${-499}

es-bills - add - invalid - create es bill with invalid required fields
    [Tags]    FET
    [Template]    Verify Es Bill Post With Invalid Fields
    402010005    add_data[0].payment_type is invalid       user_id=${User.user_id}    bill_period=${bill_period}    payment_type=0    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010005    add_data[0].payment_type is invalid       user_id=${User.user_id}    bill_period=${bill_period}    payment_type=6    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010005    add_data[0].bill_type is invalid          user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=3    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010005    add_data[0].bill_type is invalid          user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=0    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=1    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010005    add_data[0].delivery_method is invalid    user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=0    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010005    add_data[0].delivery_method is invalid    user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0    tax_rate=0    scooter_id=${Scooter.scooter_id}    penalty_amount=0    delivery_method=3    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0    amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0    addon_price_amount=0    promotion_price_amount=0    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0

es-bills - add - invalid - create es bill with invalid required without additional code
    [Tags]    FET
    [Template]    Verify Es Bill Post With Invalid Fields Without Additional Code
    604040005    Column 'bank_barcode1' cannot be null      user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0      tax_rate=0      scooter_id=${Scooter.scooter_id}    penalty_amount=0      delivery_method=1      es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0      amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0      addon_price_amount=0      promotion_price_amount=0      latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5      bank_barcode1=${None}             due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31         bill_to_email=${User.email}    previous_balance=0          previous_paid_amount=0
    604040002    ERROR: issue_date cannot be null           user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0      tax_rate=0      scooter_id=${Scooter.scooter_id}    penalty_amount=0      delivery_method=1      es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0      amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0      addon_price_amount=0      promotion_price_amount=0      latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5      bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${None}                 settle_days=31         bill_to_email=${User.email}    previous_balance=0          previous_paid_amount=0
    604040002    ERROR: settle_days cannot be null          user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0      tax_rate=0      scooter_id=${Scooter.scooter_id}    penalty_amount=0      delivery_method=1      es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0      amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0      addon_price_amount=0      promotion_price_amount=0      latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5      bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=${None}    bill_to_email=${User.email}    previous_balance=0          previous_paid_amount=0
    604040002    bill_to_email cannot be null               user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0      tax_rate=0      scooter_id=${Scooter.scooter_id}    penalty_amount=0      delivery_method=1      es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0      amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0      addon_price_amount=0      promotion_price_amount=0      latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5      bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31         bill_to_email=${None}          previous_balance=0          previous_paid_amount=0
    604040002    previous_balance cannot be null            user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0      tax_rate=0      scooter_id=${Scooter.scooter_id}    penalty_amount=0      delivery_method=1      es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0      amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0      addon_price_amount=0      promotion_price_amount=0      latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5      bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31         bill_to_email=${User.email}    previous_balance=${None}    previous_paid_amount=0
    604040002    previous_paid_amount cannot be null        user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0      tax_rate=0      scooter_id=${Scooter.scooter_id}    penalty_amount=0      delivery_method=1      es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0      amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0      addon_price_amount=0      promotion_price_amount=0      latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5      bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31         bill_to_email=${User.email}    previous_balance=0          previous_paid_amount=${None}
    604040005    Column 'store_barcode2' cannot be null     user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1    suspend_days=0    bill_type=1    adjustment_amount=0    balance=499    bill_status=${EsBill.bill_status}    tax_amount=0      tax_rate=0      scooter_id=${Scooter.scooter_id}    penalty_amount=0      delivery_method=1      es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499    over_unit_price_amount=0      amount=499    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0      addon_price_amount=0      promotion_price_amount=0      latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5      bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31         bill_to_email=${User.email}    previous_balance=0          previous_paid_amount=0

es-bills - add - invalid - create es bill with null required fields
	[Tags]    FET
	[Template]    Verify Es Bill Post With Invalid Fields
    402010006    [addData[0].userId]]; default message [must not be null]                            user_id=${None}            bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].billPeriod]]; default message [must not be null]                        user_id=${User.user_id}    bill_period=${None}           payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].paymentType]]; default message [must not be null]                       user_id=${User.user_id}    bill_period=${bill_period}    payment_type=${None}    suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].esBillScooters[0].suspendDays]]; default message [must not be null]     user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=${None}    bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].billType]]; default message [must not be null]                          user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=${None}    adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].adjustmentAmount]]; default message [must not be null]                  user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=${None}    balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].balance]]; default message [must not be null]                           user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=${None}    bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].billStatus]]; default message [must not be null]                        user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${None}                  tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].taxAmount]]; default message [must not be null]                         user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=${None}    tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].taxRate]]; default message [must not be null]                           user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=${None}    scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].esBillScooters[0].scooterId]]; default message [must not be null]       user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${None}                  penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].penaltyAmount]]; default message [must not be null]                     user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=${None}    delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].deliveryMethod]]; default message [must not be null]                    user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=${None}    es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].esBillScooters[0].esContractId]]; default message [must not be null]    user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${None}                         bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].billToName]]; default message [must not be null]                        user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=${None}             base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].basePriceAmount]]; default message [must not be null]                   user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=${None}    over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].overUnitPriceAmount]]; default message [must not be null]               user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=${None}    amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].amount]]; default message [must not be null]                            user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=${None}    date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].esBillScooters[0].dateFrom]]; default message [must not be null]        user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${None}                date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].esBillScooters[0].dateTo]]; default message [must not be null]          user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${None}              other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].otherChargeAmount]]; default message [must not be null]                 user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=${None}    addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].addonPriceAmount]]; default message [must not be null]                  user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=${None}    promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].promotionPriceAmount]]; default message [must not be null]              user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=${None}    latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    [addData[0].latestBillCalcEndDate]]; default message [must not be null]             user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${None}                     resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010005    add_data[0].es_bill_scooters[0].detail[0].resource_type is invalid                  user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=${None}    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}    issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0
    402010006    add_data[0].due_date must not be null                                               user_id=${User.user_id}    bill_period=${bill_period}    payment_type=1          suspend_days=0          bill_type=1          adjustment_amount=0          balance=499        bill_status=${EsBill.bill_status}    tax_amount=0          tax_rate=0          scooter_id=${Scooter.scooter_id}    penalty_amount=0          delivery_method=1          es_contract_id=${EsContract.es_contract_id}    bill_to_name=dataplatform_test   base_price_amount=499        over_unit_price_amount=0          amount=499        date_from=${EsBill.date_from}    date_to=${EsBill.date_to}    other_charge_amount=0          addon_price_amount=0          promotion_price_amount=0          latest_bill_calc_end_date=${EsBill.last_calc_date}    resource_type=5          bank_barcode1=${bank_barcode1}    due_date=${None}               issue_date=${EsBill.issue_date}    settle_days=31    bill_to_email=${User.email}    previous_balance=0    previous_paid_amount=0

es-bills - add - valid - create accumulated bill
    [Setup]    Create Accumulated Es Bill
    ${resp} =    Es Bills Get      es_bill_ids=${accumulated_bill_id}    request_data_type=${1}
    Verify Status Code As Expected       ${resp}                                     200
    Verify Response Contains Expected    ${resp.json()['data'][0]['es_bill_id']}     ${accumulated_bill_id}
    Verify Response Contains Expected    ${resp.json()['data'][0]['accumulated']}    1

es-bills - add - valid - create es bill with correct value
	[Template]   Verify Es Bill Post With Valid Fields
    resource_type=5    bank_barcode1=${bank_barcode1}    due_date=${EsBill.due_date}
    ...    issue_date=${EsBill.issue_date}    settle_days=31
    ...    bill_to_email=${User.email}        previous_balance=0
    ...    previous_paid_amount=0

es-bills - add - valid - create es bill with print_invoice = 1
	${bill_id} =    Create Es Bill With Required Fields    print_invoice=1
    ${bill_get} =    Es bills Get        es_bill_ids=${bill_id}
    Verify Status Code As Expected       ${bill_get}                                       200
    Verify Response Contains Expected    ${bill_get.json()['data'][0]['es_bill_id']}	   ${bill_id}
    Verify Response Contains Expected    ${bill_get.json()['data'][0]['print_invoice']}	   1

es-bills - add - valid - create es bill with print_invoice = 0
	${bill_id} =    Create Es Bill With Required Fields    print_invoice=0
    ${bill_get} =    Es bills Get        es_bill_ids=${bill_id}
    Verify Status Code As Expected       ${bill_get}                                       200
    Verify Response Contains Expected    ${bill_get.json()['data'][0]['es_bill_id']}	   ${bill_id}
    Verify Response Contains Expected    ${bill_get.json()['data'][0]['print_invoice']}	   0

es-bills - add - valid - create es bill with required fields with delivery_method
	[Template]   Verify Es Bill Post With Valid Fields
    delivery_method=1
    delivery_method=2

es-bills - add - create with taxable_amount should be pass
    [Tags]    CID:737
    ${bill_id} =    Create Es Bill With Required Fields    taxable_amount=${499}
    ${bill_get} =    Es bills Get        es_bill_ids=${bill_id}
    Verify Status Code As Expected       ${bill_get}                                        200
    Verify Response Contains Expected    ${bill_get.json()['data'][0]['es_bill_id']}	    ${bill_id}
    Verify Response Contains Expected    ${bill_get.json()['data'][0]['taxable_amount']}    ${499.0}

*** Keywords ***
# -------- Setup  Keywords --------
Setup Suite Object Variable
    ${order_number} =    Generate Random String    8    [NUMBERS]
    ${es_plan_id} =      Get Es Plan Id Via Es Plan Name    綁定 3 年 $899 方案
    Set Suite Variable    ${EsContract}    ${EsContracts('${es_plan_id}')}
    Set Suite Variable    ${Order}         ${Orders('P0${order_number}')}
    Set Suite Variable    ${User}          ${Users()}
    Set Suite Variable    ${Scooter}       ${Scooters('B22318608', 'BUS')}

Test Setup
	${timestamp} =        Evaluate    int(time.time())   time
    ${bank_barcode1} =    Generate Random String    8    [NUMBERS][UPPER]
    Set Test Variable    ${timestamp}
    Set Test Variable    ${scooters_count}    1
    Set Test Variable    ${balance_price}	  499
    Set Test Variable    ${bank_barcode1}
    Set Test Variable    ${EsBill}            ${EsBills()}

Suite Setup
    Setup Suite Object Variable
    Deliver Scooter To User

# -------- Gogoro  Keywords --------
Create Accumulated Es Bill
    Test Setup
    ${bill_id} =    Create Es Bill With Required Fields    print_invoice=0
    Set Test Variable    ${accumulated_bill_id}    ${bill_id}
    Set Test Variable    ${EsBill_new}    ${EsBills(accumulated_es_bill_id='${bill_id}',balance=998, previous_balance=499)}
    ${resp} =       Create Es Bill
    ...    ${EsBill_new}    ${EsContract}
    ...    ${User}      ${Scooter.scooter_id}
    ${EsBill_new.bill_id} =    Set Variable    ${resp.json()['data'][0]['es_bill_id']}

Create Es Bill With Required Fields
    [Documentation]    Required Fields in Swagger
    [Arguments]    ${delivery_method}=1    &{fields}
    ${resp} =    Es Bills Post
    ...    user_id=${User.user_id}          bill_period=${EsBill.bill_period}
    ...    payment_type=1                   suspend_days=0                   bill_type=1
    ...    adjustment_amount=0              balance=499                      bill_status=${EsBill.bill_status}
    ...    tax_amount=0                     tax_rate=0                       scooter_id=${Scooter.scooter_id}
    ...    penalty_amount=0                 delivery_method=${delivery_method}
    ...    es_contract_id=${EsContract.es_contract_id}
    ...    bill_to_name=dataplatform_test   base_price_amount=499            over_unit_price_amount=0
    ...    amount=499                       date_from=${EsBill.date_from}    date_to=${EsBill.date_to}
    ...    other_charge_amount=0            addon_price_amount=0             promotion_price_amount=0
    ...    latest_bill_calc_end_date=${EsBill.last_calc_date}
    ...    resource_type=5
    ...    bank_barcode1=${bank_barcode1}
    ...    store_barcode2=${EsContract.es_contract_id}
    ...    due_date=${EsBill.due_date}
    ...    issue_date=${EsBill.issue_date}
    ...    settle_days=31
    ...    bill_to_email=${User.email}
    ...    previous_balance=0
    ...    previous_paid_amount=0
    ...    &{fields}
    Verify Status Code As Expected         ${resp}                      200
    Verify Response Should Contains Key    ${resp.json()['data'][0]}    es_bill_id
    [Return]    ${resp.json()['data'][0]['es_bill_id']}

Deliver Scooter To User
    ${User.user_id} =                           Create User            ${User}
    ${Scooter.scooter_id} =                     Create Scooters        ${Scooter}
    ${Order.order_id}    ${Order.owner_id} =    Create Order           VEH_SALE_CR          ${Order.order_no}    I    ${User.user_id}    30001
    ${EsContract.es_contract_id} =              Create Es Contracts    ${Order.order_id}    ${User.user_id}    1    ${Order.owner_id}    1    ${Order.owner_id}    ${EsContract.es_plan_id}    ${EsContract.start_date}    1    1    2
    Update Scooter Contract To Delivery Approval Status    ${Order}    ${Scooter}    ${User}
    Scooters Infos Update    ${Order.order_no}    ${Scooter.vin}    ${User.user_id}    ${Order.owner_id}    ${User.gogoro_guid}    1    turn_light=1    brake_light=1    tpms=0    sport_mode=0    warranty_start=${Scooter.warranty_start}    warranty_end=${Scooter.warranty_end}

# -------- Verify  Keywords --------
Verify Es Bill Get With Invalid Fields
	[Arguments]    ${additional_code}    ${err_msg}    &{fields}
	${resp} =    Es Bills Get    &{fields}
    Verify Status Code As Expected       ${resp}    200
    Verify GoPlatform Error Message      ${resp}    ${additional_code}    ${err_msg}

Verify Es Bill Post With Invalid Fields
	[Arguments]    ${additional_code}    ${err_msg}    &{fields}
	${resp} =    Es Bills Post    &{fields}
    Verify Status Code As Expected       ${resp}    200
    Verify GoPlatform Error Message      ${resp}    ${additional_code}    ${err_msg}

Verify Es Bill Post With Invalid Fields Without Additional Code
	[Arguments]    ${additional_code}    ${err_msg}    &{fields}
	${resp} =    Es Bills Post    &{fields}
    Verify Status Code As Expected       ${resp}    200
    Verify Response Contains Expected    ${resp.json()['code']}                  -1
    Verify Response Contains Expected    ${resp.json()['data'][0]['code']}       ${additional_code}
    Should Contain                       ${resp.json()['data'][0]['message']}    ${err_msg}

Verify Es Bill Post With Valid Fields
    [Arguments]    &{fields}
    FOR    ${index}    IN RANGE    5
        ${code} =    Generate Random String    8    [NUMBERS][UPPER]
        Set Test Variable    ${code${index}}    ${code}
    END
    Set Test Variable    ${EsBill}    ${EsBills()}
    ${es_bill_id} =    Create Es Bill With Required Fields
    ...    &{fields}
    ...    bank_barcode2=${code1}
    ...    store_barcode1=${code2}
    ...    store_barcode2=${code3}
    ...    store_barcode3=${code4}
    ...    bill_to_address=${User.contact_address}
    ...    bill_to_zipcode=${User.contact_zip}
    ...    other_data=Test data
    ...    details_amount=499
    ...    tran_no=${EsBill.tran_no}
    ${resp_get} =    Es bills Get        es_bill_ids=${es_bill_id}                         request_data_type=${1}
	Verify Response Contains Expected    ${resp_get.json()['data'][0]['bank_barcode1']}	   ${bank_barcode1}
	Verify Response Contains Expected    ${resp_get.json()['data'][0]['unissued_invoice_amount']}	   ${0.0}
